# -*- coding: utf-8 -*-
"""order-flow-learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gf1u1r8AzC8A3BmlKyaAjjPpndPT9yTw

# Order Flow Alpha Lab

For this project, one of my goal is to learn how the strategy emerges in the market because I am curious about how buy/sell could infer information about what will happen in the market. This strategy is backed with theory called Auction Market Theory, aside from this you would be able to understand the mircroeconomic structure behind the strategy.

One question arises,

> Does short-term order flow imbalance contains information about the future BTC price movements?

We will go through order flow real trades, buy/sell classification, order-flow imbalance, studying its features, dealing with hypothesis, backtest, transaction cost and out of sample test.

This project is just for the purpose of learning and curiosity about the order-flow strategy in trading.

## Install libraries
"""

!pip -q install pandas numpy matplotlib seaborn requests scipy scikit-learn

import pandas as pd
import numpy as np
import requests
import time
import matplotlib.pyplot as plt
import seaborn as sns

from scipy import stats
from sklearn.metrics import classification_report, roc_auc_score

pd.set_option("display.max_columns", 100)

"""## Download real binance trade data

We are using Binance's public market-data endpoint. Binance documents $aggTrades$ a s aggregated executions from taker order, and its public market-data API does not require authentication.
"""

BASE_URL = "https://data-api.binance.vision/api/v3/aggTrades"

SYMBOL = "BTCUSDT"

def get_aggtrades(end_time=None, limit=1000):

    params = {
        "symbol": SYMBOL,
        "limit": limit
    }

    if end_time is not None:
        params["endTime"] = int(end_time)

    r = requests.get(BASE_URL, params=params, timeout=30)
    r.raise_for_status()

    return r.json()

"""Test the API"""

sample = get_aggtrades(limit=5)

sample

"""## Download approximately 30,000 recent trades"""

def download_trades(n_batches=30):

    all_data = []
    end_time = None

    for i in range(n_batches):

        data = get_aggtrades(
            end_time=end_time,
            limit=1000
        )

        if not data:
            break

        all_data.extend(data)

        oldest_time = min(x["T"] for x in data)
        end_time = oldest_time - 1

        print(
            f"Batch {i+1}/{n_batches} | "
            f"Trades collected: {len(all_data):,}"
        )

        time.sleep(0.15)

    return all_data


raw_trades = download_trades(n_batches=30)

len(raw_trades)

"""## Convert into a DataFrame"""

df = pd.DataFrame(raw_trades)

df.head()

"""Renaming columns"""

df = df.rename(columns={
    "a": "trade_id",
    "p": "price",
    "q": "quantity",
    "f": "first_trade_id",
    "l": "last_trade_id",
    "T": "timestamp",
    "m": "buyer_maker"
})

"""## Convert types"""

df["price"] = df["price"].astype(float)
df["quantity"] = df["quantity"].astype(float)

df["timestamp"] = pd.to_datetime(
    df["timestamp"],
    unit="ms",
    utc=True
)

df = df.sort_values("timestamp").drop_duplicates("trade_id")

df.reset_index(drop=True, inplace=True)

df.head()

df.info()

"""## Understanding what buyer_maker means

If buyer_maker is True means the buyer was the maker, that means the aggresive participant was the seller. Therefore selling pressure emerges. Whereas, if buyer_maker is False it means that agressive participant was the buyer, hence, buying pressure emerges.

## Create signed order flow
"""

df["side"] = np.where(
    df["buyer_maker"],
    "SELL",
    "BUY"
)

"""Now calculate dollar/national volume:"""

df["notional"] = df["price"] * df["quantity"]

"""Add signed volume:"""

df["signed_volume"] = np.where(
    df["side"] == "BUY",
    df["quantity"],
    -df["quantity"]
)

"""Also signed dollar flow:"""

df["signed_notional"] = np.where(
    df["side"] == "BUY",
    df["notional"],
    -df["notional"]
)

df[
    [
        "timestamp",
        "price",
        "quantity",
        "side",
        "notional",
        "signed_notional"
    ]
].head(20)

"""## Visualize the actual trades"""

plt.figure(figsize=(14, 5))

plt.plot(
    df["timestamp"],
    df["price"]
)

plt.title("BTCUSDT Trade Price")
plt.xlabel("Time")
plt.ylabel("Price")

plt.xticks(rotation=45)
plt.show()

"""Here, we are not working with candlesticks. We are working with individual market executions.

## Aggregate trades into 1-minute buckets

Microstructure data is extremely noisy.
"""

df = df.set_index("timestamp")

bars = df.resample("1min").agg(
    price=("price", "last"),
    volume=("quantity", "sum"),
    notional=("notional", "sum"),
    signed_volume=("signed_volume", "sum"),
    signed_notional=("signed_notional", "sum"),
    trades=("trade_id", "count")
)

bars.head()

"""Now calculate buy and sell volume."""

buy_volume = (
    df["quantity"]
    .where(df["side"] == "BUY", 0)
    .resample("1min")
    .sum()
)

sell_volume = (
    df["quantity"]
    .where(df["side"] == "SELL", 0)
    .resample("1min")
    .sum()
)

bars["buy_volume"] = buy_volume
bars["sell_volume"] = sell_volume

bars

"""## Calculate Order Flow Imbalance

Here's our primary microstructure variable:

$$
\mathrm{OFI} =
\frac{V_{\mathrm{buy}} - V_{\mathrm{sell}}}
{V_{\mathrm{buy}} + V_{\mathrm{sell}}}
$$
	​

"""

bars["ofi"] = (
    (bars["buy_volume"] - bars["sell_volume"]) /
    (bars["buy_volume"] + bars["sell_volume"])
)

"""$$
\begin{aligned}
\mathrm{OFI} &\approx +1 && \quad \text{Extremely buy-dominated} \\
\mathrm{OFI} &\approx 0  && \quad \text{Balanced buying and selling} \\
\mathrm{OFI} &\approx -1 && \quad \text{Extremely sell-dominated}
\end{aligned}
$$
"""

bars["ofi"].describe()

"""## Plot Order Flow"""

plt.figure(figsize=(14, 5))

plt.plot(
    bars.index,
    bars["ofi"]
)

plt.axhline(0)

plt.title("BTCUSDT Order Flow Imbalance")
plt.ylabel("OFI")

plt.xticks(rotation=45)
plt.show()

"""This is pretty much different from what traditional technical analysis give us. We are now seeing in a way how buyers and sellers doing tug-of-war.

Question arises from this plot such as,

> Who is aggresively transating?

rather than simply saying

> What shape did the candle make?

## Now we calculate the returns
"""

bars["return_1m"] = bars["price"].pct_change()

"""Future return:"""

bars["future_return_1m"] = (
    bars["price"].shift(-1) / bars["price"] - 1
)

"""And a 5-minute future return"""

bars["future_return_5m"] = (
    bars["price"].shift(-5) / bars["price"] - 1
)



"""## Research Hypothesis

Hypothesis:

> Strong positive order-flow imbalance should be associated with positive subsequent returns.


We can divide OFI into quantiles.
"""

bars["ofi_quantile"] = pd.qcut(
    bars["ofi"],
    5,
    labels=[
        "Very Low",
        "Low",
        "Neutral",
        "High",
        "Very High"
    ]
)

"""Calculate future returns:"""

group_returns = (
    bars
    .groupby("ofi_quantile", observed=True)["future_return_5m"]
    .agg(["mean", "median", "std", "count"])
)

group_returns

"""## Visualizing the relationship"""

group_returns["mean"].plot(
    kind="bar",
    figsize=(10, 5)
)

plt.axhline(0)

plt.title(
    "Future 5-Minute Return by Order Flow Imbalance"
)

plt.ylabel("Average Future Return")

plt.show()

"""## Test Correlation"""

clean = bars[
    ["ofi", "future_return_5m"]
].dropna()

corr, pvalue = stats.pearsonr(
    clean["ofi"],
    clean["future_return_5m"]
)

print("Correlation:", corr)
print("P-value:", pvalue)

"""## Spearman correlation"""

spearman_corr, spearman_p = stats.spearmanr(
    clean["ofi"],
    clean["future_return_5m"]
)

print("Spearman correlation:", spearman_corr)
print("P-value:", spearman_p)

"""## Create a simple order-flow strategy

Now we turn the research hypothesis into a trading rule.

Let's say for example:

> OFI > 0.30 --> LONG

> OFI < -0.30 --> SHORT

Otherwise,

> NO TRADE
"""

bars["signal"] = 0

bars.loc[bars["ofi"] > 0.30, "signal"] = 1
bars.loc[bars["ofi"] < -0.30, "signal"] = -1

"""## Avoiding look-ahead bias

We cannot use the current minute's completed order flow to pretend we entered at the beginning of the same minimute. So we shift the signal
"""

bars["position"] = bars["signal"].shift(1)

"""Now the strategy uses:

$$ OFI_t \rightarrow signal_t \rightarrow position_{t+1} $$

rather than cheating with future information.

## Strategy returns
"""

bars["strategy_return"] = (
    bars["position"] *
    bars["return_1m"]
)

"""Calculate cumulative performance"""

bars["equity"] = (
    1 + bars["strategy_return"].fillna(0)
).cumprod()

"""Plot"""

plt.figure(figsize=(14, 6))

plt.plot(
    bars.index,
    bars["equity"]
)

plt.title("Order Flow Strategy Equity Curve")

plt.ylabel("Growth of $1")

plt.xticks(rotation=45)

plt.show()

"""## Adding transaction costs

Suppose we assume:
"""

COST = 0.0005

"""That's about 0.05 % per trade

Calculate turnover:
"""

bars["trade"] = (
    bars["position"]
    .diff()
    .abs()
)

"""Apply costs"""

bars["strategy_return_net"] = (
    bars["strategy_return"]
    -
    bars["trade"] * COST
)

bars["equity_net"] = (
    1 + bars["strategy_return_net"].fillna(0)
).cumprod()

"""Plotting it both"""

plt.figure(figsize=(14, 6))

plt.plot(
    bars.index,
    bars["equity"],
    label="Gross"
)

plt.plot(
    bars.index,
    bars["equity_net"],
    label="Net"
)

plt.title("Order Flow Strategy: Gross vs Net")

plt.legend()

plt.xticks(rotation=45)

plt.show()

"""## Calculate performance statistics"""

returns = bars["strategy_return_net"].dropna()

total_return = (1 + returns).prod() - 1

annualized_return = (
    (1 + total_return)
    ** (365 * 24 * 60 / len(returns))
    - 1
)

annualized_vol = (
    returns.std() *
    np.sqrt(365 * 24 * 60)
)

sharpe = (
    annualized_return / annualized_vol
    if annualized_vol != 0 else np.nan
)

win_rate = (
    (returns > 0).mean()
)

print("Total return:", total_return)
print("Annualized return:", annualized_return)
print("Annualized volatility:", annualized_vol)
print("Sharpe:", sharpe)
print("Win rate:", win_rate)

"""## Maximum drawdown"""

equity = bars["equity_net"].dropna()

running_max = equity.cummax()

drawdown = (
    equity / running_max - 1
)

max_drawdown = drawdown.min()

print(
    "Maximum drawdown:",
    max_drawdown
)

"""Plot"""

plt.figure(figsize=(14, 5))

plt.plot(
    drawdown.index,
    drawdown
)

plt.axhline(0)

plt.title("Strategy Drawdown")

plt.ylabel("Drawdown")

plt.xticks(rotation=45)

plt.show()

"""## Machine learning extension

Create additional features:
"""

bars["ofi_3"] = bars["ofi"].rolling(3).mean()

bars["ofi_5"] = bars["ofi"].rolling(5).mean()

bars["ofi_10"] = bars["ofi"].rolling(10).mean()

bars["volume_z"] = (
    (bars["volume"] - bars["volume"].rolling(30).mean())
    /
    bars["volume"].rolling(30).std()
)

bars["return_1"] = bars["price"].pct_change()

bars["volatility"] = (
    bars["return_1"]
    .rolling(20)
    .std()
)

"""Create target:"""

bars["target"] = (
    bars["future_return_5m"] > 0
).astype(int)

"""## ML dataset"""

features = [
    "ofi",
    "ofi_3",
    "ofi_5",
    "ofi_10",
    "volume_z",
    "return_1",
    "volatility"
]

ml_data = bars[
    features + ["target"]
].dropna()

X = ml_data[features]
y = ml_data["target"]

"""## Time-series train/test split

Use chronological splitting.
"""

split = int(len(ml_data) * 0.70)

X_train = X.iloc[:split]
X_test = X.iloc[split:]

y_train = y.iloc[:split]
y_test = y.iloc[split:]

"""## Using logistic regression"""

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

model = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression())
])

model.fit(
    X_train,
    y_train
)

probabilities = model.predict_proba(X_test)[:, 1]

predictions = (
    probabilities > 0.5
).astype(int)

"""## Evaluating the performance"""

print(
    classification_report(
        y_test,
        predictions
    )
)

"""AUC:"""

auc = roc_auc_score(
    y_test,
    probabilities
)

print("Out-of-sample ROC-AUC:", auc)

"""## Examine which features matter"""

coefs = pd.Series(
    model.named_steps["model"].coef_[0],
    index=features
)

coefs.sort_values().plot(
    kind="barh",
    figsize=(10, 6)
)

plt.title("Microstructure Feature Coefficients")

plt.show()

